### ISSUE TITLE
Python errror by Mängel import

### ISSUE THREAD

**Issue by mbernasocchi** [opengisch/veriso#29]
Beim Import der Maengel gibt es noch folgendes Problem:
Beim Shapefile: Der Import läuft ohne Fehlermeldung durch, das importierte File ist aber leer (0 features).
Bei Excel: Es kommt als python error die angehängte Fehlermeldung. Es scheint ein Problem mit dem unicode zu sein..
Getestet habe ich mit den files im Ordner Share/AVOR_PNF2.1/Bolligen/

![image](https://user-images.githubusercontent.com/233663/29092963-67e36034-7c88-11e7-90cb-57529e499e33.png)

**Comment by marioba** [comment]
![image](https://user-images.githubusercontent.com/24844357/29968974-5efba3fc-8f1e-11e7-9ec6-1754a84458a2.png)

We should warn if it's not possible to import the shape file correctly.

**Comment by marioba** [comment]
Ask to mr. VeriBe if he want we correct the Shapefile

**Comment by marioba** [comment]
The excel file seems to be written with a strange encoding
