### ISSUE TITLE
Sortierung anpassen

### ISSUE THREAD

**Issue by mbernasocchi** [opengisch/veriso#41]
![image](https://user-images.githubusercontent.com/233663/31670183-54febe7c-b357-11e7-82da-9eca88f84459.png)

**Comment by marioba** [comment]
@mbernasocchi I tried on test.veribe.alpgis.ch and the list is correctly sorted both with old projects and newly imported ones. I'm trying to understand why by Tobias are not sorted.

![image](https://user-images.githubusercontent.com/24844357/31703982-7c08942e-b3df-11e7-9c14-4eeef0ec740f.png)

**Comment by mbernasocchi** [comment]
I asked Tobias to give us feedback here

**Comment by mbernasocchi** [comment]
From Tobias: I tried it again on the test server today and the sorting of the list was correct.
But the sorting of the ogc_fid is not.
